[package]
name = "recapnc"
version = "0.0.0"
description = "A library for bootstrapping the recapn library"
authors = ["Sydney Acksman <obsidianminor@gmail.com>"]
edition = "2018"

[[bin]]
name = "capnpc-rust"
path = "src/bin.rs"

[dependencies]
recapn = { path = "../recapn" }
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
anyhow = "1.0"
unicode-ident = "1.0"
heck = "0.4"
prettyplease = "0.2"