[package]
name = "recapn-rpc"
version = "0.0.0"
authors = ["Sydney Acksman <obsidianminor@gmail.com>"]
edition = "2018"

[dependencies]
recapn = { path = "../recapn" }
fnv = "1.0"
tokio = { version = "1.29", default-features = false, features = ["rt", "macros", "sync"] }
pin-project = "1.1"
parking_lot = "0.12"