[package]
name = "recapn"
version = "0.1.0"
authors = ["Sydney Acksman <obsidianminor@gmail.com>"]
edition = "2021"

[features]
default = ["std"]
alloc = []
std = ["tinyvec", "alloc"]

[dependencies]
tinyvec = { version = "1.6", features = ["rustc_1_40", "alloc"], optional = true }