name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install capnp
        run: sudo apt-get install -y capnproto
      - uses: actions/checkout@v4
      - name: Install latest stable Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Test no default features
        run: cargo test --all --no-default-features
      - name: Test all features
        run: cargo test --all --all-features
